### ISSUE TITLE
Documentation or examples would be much appreciated.

### ISSUE THREAD

**Issue by dieki-n** [graycatlabs/usb-c-arduino#1]
I'm trying to get this working on my board, but it's not clear how the library is supposed to be used. Documentation or examples of the function calls necessary to, e.g., request a specific voltage would be much appreciated.

**Comment by signal-audio** [comment]
Strongly agree. It's quite unclear the nature of the USB-C transaction, even (especially?!) from the FUSB302B datasheet.
The two key things I would like to understand are how to negotiate the voltage, and whether this is a set it once affair or if this needs to be continually renegotiated.

**Comment by dieki-n** [comment]
What I've determined is that the FUSB302B doesn't actually handle power negotiation for you itself; it just gives you access to the USB PD protocol layer, and then you must send commands over that protocol to negotiate power.  The USB PD spec contains details about the protocol, which has been somewhat helpful: https://www.usb.org/document-library/usb-power-delivery

Still haven't gotten this library working though. Once the next revision of my board comes back I'll take another go at it.

**Comment by graycat** [comment]
Oops, this is a forgotten WIP repo and probably shouldn't be public. I'd recommend heading over to [Reclaimer Labs](https://www.reclaimerlabs.com/blog/tag/usb-c) for some good USB-C info. The [USB-C Explorer](https://www.tindie.com/products/reclaimerlabs/usb-c-explorer/
) is a great way to get started, and the [default firmware](https://github.com/ReclaimerLabs/USB-C-Explorer) does voltage negotiation. Good luck!
